name: CICD Automation Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'

jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing

    steps:
      - name: Set Private Build
        run: echo "::set-output name=private_build::true"
          if: github.event.inputs.private_build == 'false'

      - name: Use Private Build
        run: echo "Private Build value:${{ needs.enforce_private_build.outputs.private_build }}"
