name: CICD Automation Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'

jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing

    steps:
      - name: Set Private Build
        run: echo "private_build=${{ github.event.inputs.branch == 'master' || github.event_name == 'workflow_dispatch' }}" >> $GITHUB_ENV
 
      - name: Use Private Build
        run: echo "Private Build value:${{ env.private_build }}"
        env:
          private_build: ${{ github.event.inputs.private_build }}
