name: CICD Automation Testing
 
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'
 
jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing
 
    steps:
      - name: Enforce Private Build
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.branch }}" == "master" ] && [ "${{ github.event.inputs.private_build }}" == "false" ]; then
              sed -i 's/private_build: '\''false'\''/private_build: '\''true'\''/' $GITHUB_WORKSPACE/.github/workflows/main.yml
            fi
          fi
 
      - name: Print Input Values
        run: |
          echo "Input values:"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Private Build: ${{ github.event.inputs.private_build }}"
