name: CICD Automation Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'

jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing

    steps:
      - name: Enforce Private Build
        run: echo "::set-input name=private_build::true"
        if: github.event.inputs.branch == 'master' || github.event_name == 'workflow_dispatch'

      - name: Use Private Build
        run: echo "Private Build value:${{ github.event.inputs.private_build || inputs.private_build }}"

