name: CICD Automation Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'

jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing

    steps:
      - name: Enforce Private Build
        run: |
          if [ "${{ github.event.inputs.private_build }}" == 'false' ]; then
            echo "private_build=true" >> $GITHUB_ENV
          else
            echo "private_build=${{ github.event.inputs.private_build }}" >> $GITHUB_ENV
          fi
 
      - name: Use Private Build
        run: echo "Private Build value:${{ env.private_build }}"
