on:
  push:
    branches:
      - cicd_pipeline
  workflow_call:
    inputs:
      private_build:
        description: 'Private Build {true, false}'
        type: string
        required: true
        default: 'true'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'
 
jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing
 
    steps:
      - name: Set Private Build
        run: echo "private_build='true'" >> $GITHUB_ENV
        # Enforce private_build='true' if triggered on 'master'
        if: github.event.inputs.branch == 'master'
 
      - name: Print Input Values
        run: |
          echo "Input values:"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Private Build: ${{ github.event.inputs.private_build }}"
          echo "Actual private_build value: $private_build"
 
