name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'Input Parameter 1'
        required: true
        default: 'Default Value 1'
      parameter2:
        description: 'Input Parameter 2'
        required: false
        default: 'Default Value 2'

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Manual Trigger Workflow
      run: |
        echo "Input Parameter 1: ${{ github.event.inputs.parameter1 }}"
        echo "Input Parameter 2: ${{ github.event.inputs.parameter2 }}"
