name: CICD Automation Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      private_build:
        description: 'Private Build {true, false}'
        required: true
        default: 'false'  # Default to false

jobs:
  enforce_private_build:
    runs-on: ubuntu-latest
    name: CICD Automation Testing

    steps:
      - name: Set Private Build
        run: echo "private_build=true" >> $GITHUB_ENV
 
      - name: Use Private Build
        run: echo "Private Build value:${{ github.event.inputs.private_build }}"
